FROM pytorch/pytorch@sha256:4ec910830ec6c3b837d5621b6f995a31638d3b0824bf0ed4fcaeba7dd4f89b48
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir --no-deps torchvision==0.25.0
COPY src ./src
COPY scripts ./scripts
ENV PYTHONPATH=/app/src
CMD ["python", "scripts/train_pretrained_ensemble.py"]
